site_name: django-rest-xauth
repo_url: https://github.com/ajharry69/django-rest-xauth/
site_author: Orinda Harrison
nav:
  - Home: index.md
  - API guide:
      - Settings: api-guide/settings.md
theme: readthedocs