from datetime import timedelta

from django.conf import settings

__all__ = [
    "XAUTH_ENFORCE_ACCOUNT_VERIFICATION",
    "ACCESS_TOKEN_EXPIRY",
    "TOKEN_EXPIRY",
    "VERIFICATION_CODE_EXPIRY",
    "TEMPORARY_PASSWORD_EXPIRY",
    "REPLY_TO_ACCOUNTS_EMAIL_ADDRESSES",
    "DATE_INPUT_FORMAT",
    "ACCOUNT_ACTIVATION_TOKEN_EXPIRY",
    "REQUEST_TOKEN_ENCRYPTED",
]

XAUTH_ENFORCE_ACCOUNT_VERIFICATION = getattr(settings, "XAUTH_XAUTH_ENFORCE_ACCOUNT_VERIFICATION", True)
ACCESS_TOKEN_EXPIRY = TOKEN_EXPIRY = getattr(settings, "XAUTH_ACCESS_TOKEN_EXPIRY", timedelta(days=1))
VERIFICATION_CODE_EXPIRY = getattr(settings, "XAUTH_VERIFICATION_CODE_EXPIRY", timedelta(minutes=5))
TEMPORARY_PASSWORD_EXPIRY = getattr(settings, "XAUTH_TEMPORARY_PASSWORD_EXPIRY", timedelta(minutes=5))
REPLY_TO_ACCOUNTS_EMAIL_ADDRESSES = getattr(settings, "XAUTH_REPLY_TO_ACCOUNTS_EMAIL_ADDRESSES", [])
DATE_INPUT_FORMAT = getattr(settings, "XAUTH_DATE_INPUT_FORMAT", settings.DATE_INPUT_FORMATS[0])
ACCOUNT_ACTIVATION_TOKEN_EXPIRY = getattr(settings, "XAUTH_ACCOUNT_ACTIVATION_TOKEN_EXPIRY", timedelta(minutes=5))
REQUEST_TOKEN_ENCRYPTED = getattr(settings, "XAUTH_GENERATE_ENCRYPTED_TOKENS", True)
